SK-2343: Maintain the Java v2 SDK's code and documentation in the main branch (#253)
* SK-1817: Public release Java SDK 2.0.0 (#222)

diff --git a/.github/workflows/shared-build-and-deploy.yml b/.github/workflows/shared-build-and-deploy.yml
--- a/.github/workflows/shared-build-and-deploy.yml
+++ b/.github/workflows/shared-build-and-deploy.yml
@@ -3,22 +3,22 @@ on:
   workflow_call:
     inputs:
       ref:
-        description: 'Git reference to use (e.g., main or branch name)'
+        description: "Git reference to use (e.g., main or branch name)"
         required: true
         type: string
-
-      is-internal:
-        description: 'Flag for internal release'
-        required: true
-        type: boolean
 
       server-id:
-        description: 'Id of the repository'
+        description: "Id of the repository"
         required: true
         type: string
-      
+
       profile:
-        description: 'Profile to pick from pom.xml'
+        description: "Profile to pick from pom.xml"
+        required: true
+        type: string
+
+      tag:
+        description: 'Release Tag'
         required: true
         type: string
     secrets:
@@ -34,25 +34,46 @@ on:
       gpg-passphrase:
         required: true
 
+      skyflow-credentials:
+        required: true
+
+      test-expired-token:
+        required: true
+
+      test-reusable-token:
+        required: true
+
 jobs:
   publish:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
-          ref: ${{ inputs.ref }}
           fetch-depth: 0
 
       - name: Set up maven or jfrog repository
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v4
         with:
-          java-version: '1.8'
-          distribution: 'adopt'
+          java-version: "11"
+          distribution: "adopt"
           server-id: ${{ inputs.server-id }}
           server-username: SERVER_USERNAME
           server-password: SERVER_PASSWORD
           gpg-private-key: ${{ secrets.gpg-key }} # Value of the GPG private key to import
           gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
+      
+      - name: Resolve Branch for the Tagged Commit
+        id: resolve-branch
+        if: ${{ inputs.tag == 'beta' || inputs.tag == 'public' }} 
+        run: |
+          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})
+          BRANCH_NAME=$(git branch -r --contains $TAG_COMMIT | grep -o 'origin/.*' | sed 's|origin/||' | head -n 1)
+          if [ -z "$BRANCH_NAME" ]; then
+            echo "Error: Could not resolve branch for the tag."
+            exit 1
+          fi
+          echo "Resolved Branch Name: $BRANCH_NAME"
+          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
 
       - name: Get Previous tag
         id: previoustag
@@ -63,7 +84,7 @@ jobs:
       - name: Bump Version
         run: |
           chmod +x ./scripts/bump_version.sh
-          if ${{ inputs.is-internal }}; then
+          if ${{ inputs.tag == 'internal' }}; then
             ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}" "$(git rev-parse --short "$GITHUB_SHA")"
           else
             ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}"
@@ -73,22 +94,28 @@ jobs:
         run: |
           git config user.name ${{ github.actor }}
           git config user.email ${{ github.actor }}@users.noreply.github.com
+
+          if [[ "${{ inputs.tag }}" == "beta" || "${{ inputs.tag }}" == "public" ]]; then
+            git checkout ${{ env.branch_name }}
+          fi
+
           git add pom.xml
-          if ${{ inputs.is-internal }}; then
+          if [[ "${{ inputs.tag }}" == "internal" ]]; then
             git commit -m "[AUTOMATED] Private Release ${{ steps.previoustag.outputs.tag }}-dev-$(git rev-parse --short $GITHUB_SHA)"
             git push origin ${{ github.ref_name }} -f
-          else
+          fi
+          if [[ "${{ inputs.tag }}" == "beta" || "${{ inputs.tag }}" == "public" ]]; then
             git commit -m "[AUTOMATED] Public Release - ${{ steps.previoustag.outputs.tag }}"
-            git push origin
+            git push origin ${{ env.branch_name }}
           fi
 
       - name: Create env
-        if: ${{ inputs.is-internal }}
         id: create-env
         run: |
           touch .env
-          echo SKYFLOW_CREDENTIALS=${{ secrets.SKYFLOW_CREDENTIALS }} >> .env
-          echo TEST_EXPIRED_TOKEN=${{ secrets.TEST_EXPIRED_TOKEN }} >> .env
+          echo SKYFLOW_CREDENTIALS=${{ secrets.skyflow-credentials }} >> .env
+          echo TEST_EXPIRED_TOKEN=${{ secrets.test-expired-token }} >> .env
+          echo TEST_REUSABLE_TOKEN=${{ secrets.test-reusable-token }} >> .env
 
       - name: Create credentials json
         id: create-json
@@ -98,7 +125,8 @@ jobs:
           json: ${{ secrets.TEST_CREDENTIALS_FILE_STRING }}
 
       - name: Publish package
-        run: mvn clean deploy -P ${{ inputs.profile }}
+        run: mvn --batch-mode deploy -P ${{ inputs.profile }}
+
         env:
           SERVER_USERNAME: ${{ secrets.server-username }}
           SERVER_PASSWORD: ${{ secrets.server-password  }}
